### ISSUE TITLE
Camera pop in/reset

### ISSUE THREAD

**Issue by Mizerka** [z3lx/genshin-fov-unlock#2]
Hey, thanks for this, good job :)

just trying it out for first time, and I sporadically get this odd popping in issue, almost like the camera is snapping back into normal pov rather than staying locked in, this is mostly seen while exploring but in some areas its constant.

running latest v3.3 unlocker with 180fps at 1440p, borderless and fullscreen behave the same way.

video example
https://streamable.com/k5tolw

**Comment by z3lx** [comment]
You can try increasing the `threshold` key in the config to `5.0`. This is a limitation on the plugin's end, and there isn't really a foolproof fix unless it hooks into more of the game's functions, which would be much riskier. 

Fundamentally, the issue is that the plugin tracks the number of times the hooked function's been called each frame to determine whether or not to override the FOV, but there isn't a reliable way of checking when a frame starts and when it ends. So, for the time being, it's just tracking the time between each call, and if it's above a certain `threshold`, it considers it a new frame. If your camera keeps popping in and out, it suggests that you might be experiencing an inconsistent frame time (microstutters), and that increasing the `threshold` might help.

I'll add an option into the config to disable FOV interpolation based on this heuristic approach. It will fix the popping in and out issue, but will break other things such as character ULTs that changes the camera's FOV (so almost every character).

**Comment by z3lx** [comment]
For now though, you can try these settings:
- `120` FPS in the unlocker
- `8.0` threshold in the fov config

**Comment by Mizerka** [comment]
thanks for quick reponse; it really didnt like 8 haha, changing to 2.0

**Comment by z3lx** [comment]
Yeah sorry about that lol
I had to refresh my memory on how the internals worked before realizing that what I've said applies to the opposite case where FPS is too low but threshold too high

**Comment by Mizerka** [comment]
setting 2.0 and 120fps (gsync 180, 75% is fine for me), seems to have done the trick for me.

also enabled frametime views on monitoring tool, added video to oringinal comment btw, went back to same spot and can see frametime is jittery in that exact spot for whatever reason. on average it hovers at 7ms with +- 1ms variance without jitter or spikes, this is with 3dgimi loaded btw where most of frametime increases and fps drops would come from.

I'll see how it goes, thanks for your help. finally a usable camera :)

**Comment by z3lx** [comment]
> I'll add an option into the config to disable FOV interpolation based on this heuristic approach. It will fix the popping in and out issue, but will break other things such as character ULTs that changes the camera's FOV (so almost every character).

I've merged #4 and drafted a [new release](https://github.com/z3lx/genshin-fov-unlock/releases/tag/v1.1.3) that adds the option of just disabling interpolation.

**Comment by z3lx** [comment]
I just merged #9 which should completely eliminate this particular issue. It removes time-dependent frame counting and replaces it with an algorithm that's a lot more stable in my testing. This feature will be included in the next release when the game updates to 5.2.
